apiVersion: v1
kind: Service
metadata:
  name: image-fetcher
  labels:
    app: image-fetcher
spec:
  ports:
    - port: 50051
  selector:
    app: image-fetcher
    tier: app
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-fetcher
  labels:
    app: image-fetcher
spec:
  selector:
    matchLabels:
      app: image-fetcher
      tier: app
  template:
    metadata:
      labels:
        app: image-fetcher
        tier: app
    spec:
      containers:
        - image: hatena-intern-2020-image-fetcher
          imagePullPolicy: Never
          name: image-fetcher
          env:
            - name: GRPC_PORT
              value: "50051"
          envFrom:
            - configMapRef:
                name: image-fetcher-app-env-vars
          resources:
            requests:
              cpu: 100m
              memory: 10Mi
            limits:
              cpu: 200m
              memory: 20Mi
          ports:
            - containerPort: 50051
              name: image-fetcher
          readinessProbe:
            exec:
              command:
                [
                  "/bin/grpc_health_probe",
                  "-addr=:50051",
                  "-connect-timeout=5s",
                  "-rpc-timeout=5s",
                ]
            initialDelaySeconds: 5
          livenessProbe:
            exec:
              command:
                [
                  "/bin/grpc_health_probe",
                  "-addr=:50051",
                  "-connect-timeout=5s",
                  "-rpc-timeout=5s",
                ]
            initialDelaySeconds: 10
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - all
              add:
                - NET_BIND_SERVICE
            readOnlyRootFilesystem: true
