name: CI

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/ci.yml"
      - "services/**"
      - "!**.md"
  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - "services/**"
      - "!**.md"

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        service:
          - renderer-go
          - fetcher
          - image-fetcher
    defaults:
      run:
        shell: bash
        working-directory: services/${{ matrix.service }}
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Setup Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: "1.14"

      - run: go mod download
      - run: make fmt
      - run: make test
      - run: make build
