name: CI

on:
  push:
    branches:
      - master
    paths:
      - 'services/**'
      - '**.md'
  pull_request:
    paths:
      - 'services/**'
      - '**.md'

jobs:
  skipci:
    runs-on: ubuntu-18.04
    steps:
      - run: echo "[skip ci] ${{ contains(github.event.head_commit.message, '[skip ci]') }}"

  renderer-go:
    runs-on: ubuntu-18.04
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    defaults:
      run:
        shell: bash
        working-directory: services/renderer-go
    steps:
      - uses: actions/checkout@v2.3.2

      - name: Setup Go
        uses: actions/setup-go@v2.1.2
        with:
          go-version: '1.14'

      - run: go mod download
      - run: make fmt
      - run: make test
      - run: make build
